#!/usr/bin/with-contenv bash
# shellcheck shell=bash

shopt -s globstar

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 5000" \
    cd /app/www/public/backend/build s6-setuidgid abc /usr/bin/npm run start --logs-dir /config/log/npm
