#!/usr/bin/with-contenv bash

DEFAULT_CONF="/config/nginx/site-confs/default.conf"
OLD_ROOT="root /app/budge/frontend/build;"
NEW_ROOT="root /app/www/public/frontend/build;"

if grep -q "${OLD_ROOT}" "${DEFAULT_CONF}" 2>/dev/null;then
    echo "updating root in ${DEFAULT_CONF}"
    sed -i "s|${OLD_ROOT}|${NEW_ROOT}|" "${DEFAULT_CONF}"
fi
