#!/usr/bin/with-contenv bash

cd /app/budge/backend

touch /app/budge/backend/budge.sqlite

# copy config
[[ ! -e /config/config.js ]] && \
	mv /app/budge/backend/build/ormconfig.js /config/config.js

ln -sf /config/config.js /app/budge/backend/build/ormconfig.js

# permissions
chown -R abc:abc \
	/app/budge \
	/config
