#!/usr/bin/with-contenv bash

cd /app/budge/backend

touch /app/budge/backend/budge.sqlite

# copy config
[[ ! -e /config/budge.db ]] && \
	mv /app/budge/backend/budge.sqlite

ln -sf /config/budge.db /app/budge/backend/budge.sqlite

# permissions
chown -R abc:abc \
	/app/budge \
	/config
