#!/usr/bin/with-contenv bash

if [ -d /app/budge/backend/node_modules-tmp ]; then
    echo "New container detected. Setting up app folder and fixing permissions."
    mv /app/budge/backend/node_modules-tmp /app/budge/backend/node_modules
	mv /app/budge/frontend/node_modules-tmp /app/budge/frontend/node_modules
fi

cd /app/budge/backend

touch /app/budge/backend/budge.sqlite

# copy config
[[ ! -e /config/config.js ]] && \
	mv /app/budge/backend/build/ormconfig.js /config/config.js

ln -sf /config/config.js /app/budge/backend/build/ormconfig.js

# permissions
chown -R abc:abc \
	/app/budge \
	/config
